### ISSUE TITLE
Which service are you using ?

### ISSUE THREAD

**Issue by techieforgood** [pawelgrzybek/pawelgrzybek.com#135]
Hey, I came across your blog and enjoyed your style and content.
I found the comment system to be quite clean. Which service are you using ?
I did observe that the data is submitted as JSON to an AWS end point. But could not figure out more.

**Comment by pawelgrzybek** [comment]
Hi @techieforgood.

Because I couldn't find anything that I like, I build my own one. I described the general idea here: https://pawelgrzybek.com/i-built-a-thing-jamstack-commenting-system-using-aws-cdk-api-gateway-lambda-and-dynamodb/.

It is actually open sourced and you can find a link to the repo here: https://github.com/pawelgrzybek/comments-stack

**Comment by techieforgood** [comment]
Thanks Pawel for the links. I'm really interested in deploying it. Do you
have any guide to do that ?

**Comment by pawelgrzybek** [comment]
It is super simple to deploy as long as you know some basics of AWS and CDK. Pretty much `git clone` and `cdk deploy`. I need to warn you that some of the things on my commenting system are very opinionated decisions, like nested comments and not collecting emails at all. But it all can be quite easily adjusted to your needs, so it still should work great as a starting point.

**Comment by techieforgood** [comment]
Thanks a lot @pawelgrzybek for the details.
