### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by BirkhoffLee** [pawelgrzybek/pawelgrzybek.com#52]
Hey. I came across your blog and found the style very clean. I'm wondering what is the open-source license for this repository? :)

**Comment by pawelgrzybek** [comment]
Hi.

Because it is personal blog there is no licence as I thought there is no need for it for such a a personal thing. You are not the first oen asking for the theme. I am planning to release my theme as a standalone Hugo theme. For the timne being you have my unofficial permission to use my website as a base for you project my friend :)

Good luck with writing and have a lovely day :)
